### PR TITLE
upgrade train to python 3 and tensorflow r0.11

### PR DESCRIPTION
**Pull request by Arn-O**
For Python 3:

+ add parenthesis to ``print``
+ change ``cPickle`` to ``pickle`` and open files as binary
+ change ``xrange`` to ``range``

For TensorFlow r0.11:

+ force concatenate instead of tuple for the LSTM states
+ train and regenerate checkpoints 

So only minor updates. To be noticed, at some point in time the concatenate will no longer be supported, so that will pop up as an issue in a next release of TensorFlow.

### CODE REVIEW

**Comment by hardmaru** [comment]
thanks so much!

**Comment by Arn-O** [comment]
That was a great pleasure.

One day, I will try to implement the handwriting synthesis from a char string like in the demo. As of now that looks too challenging for me.

**Comment by hardmaru** [comment]
Personally I have a preference for the unconditional generation of vectors, compared to enforcing synthesis from a char string, since I'm curious to see what the machine 'dreams' about.  I'm more interested to improve and extend the other project [sketch-rnn](https://github.com/hardmaru/sketch-rnn) to get it to product more interesting and richer types of vector drawings.

**Comment by Arn-O** [comment]
Right, this is sketch-rnn is far more creative! I will give it a try either.

**Pull request merged**
